import { tokensGenerated, tokensUsed } from "../../repositories/Tokens";

function ValidateResetPasswordToken(token: string) {
  const tokenGenerated = tokensGenerated.find(
    (storedToken) => token === storedToken
  );

  // if token was not generated by the server, return false
  if (!tokenGenerated) return false;

  const tokenUsed = tokensUsed.find((storedToken) => token === storedToken);

  // if the token was already used, return false
  if (tokenUsed) return false;

  if (tokenGenerated && !tokenUsed) {
    return true;
  }
}

export default ValidateResetPasswordToken;
